import { type NextPage } from "next";
import Head from "next/head";
const SinglePostPage: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center">
        <div>Profile View</div>
      </div>
    </>
  );
};

export default SinglePostPage;
